DROP TABLE IF EXISTS TEST_TABLE_IMPORT;
CREATE TABLE TEST_TABLE_IMPORT(ID INT PRIMARY KEY, NAME VARCHAR(255));
INSERT INTO TEST_TABLE_IMPORT VALUES(1, 'Hello');
INSERT INTO TEST_TABLE_IMPORT VALUES(2, 'World');
INSERT INTO TEST_TABLE_IMPORT VALUES(3, 'Java');