//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 08:42:36 PM IST 
//


package com.bank.ws.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bank.ws.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AccountTypes_QNAME = new QName("http://bank.com/ns", "accountTypes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bank.ws.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccountTypeWrapper }
     * 
     */
    public AccountTypeWrapper createAccountTypeWrapper() {
        return new AccountTypeWrapper();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountTypeWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bank.com/ns", name = "accountTypes")
    public JAXBElement<AccountTypeWrapper> createAccountTypes(AccountTypeWrapper value) {
        return new JAXBElement<AccountTypeWrapper>(_AccountTypes_QNAME, AccountTypeWrapper.class, null, value);
    }

}
